def extract_sql_from_output(model_output: str):
     """
    Extracts the SQL query from model output.

    Args:
        model_output (str): The raw text output generated by the model.

    Returns:
        str or None: The extracted SQL query if found, otherwise None.
    """
     
     lines = model_output.splitlines()
     for line in lines:
        if line.lower().startswith("sql:"):
            return line.split(":", 1)[1].strip()
     return None
